### ISSUE TITLE
This does not work in React native v0.52.3 

### ISSUE THREAD

**Issue by NamrataDwivedi** [react-community/react-native-image-picker#812] opened 2018-03-16 09:05 UTC
I checked this on react native v0.52.0 and it works properly but does not work in v0.52.3

**Comment by MrHubble** [comment] 2018-03-21 02:06
Are you able to expand on how it doesn't work? What is the error that is being thrown or what unexpected behaviour are you seeing? Do you have a code sample?

**Comment by NamrataDwivedi** [comment] 2018-03-23 13:29
Managed to fix the issue. Thank you.

**Comment by MrHubble** [comment] 2018-03-24 01:20
@NamrataDwivedi happy to hear. Could you please close this issue then? Thanks.

**Comment by tarekgabarin** [comment] 2018-04-06 17:11
@MrHubble How did you get it to work, I am facing the same issue

**Comment by MrHubble** [comment] 2018-04-07 02:06
@tarekgabarin it was @NamrataDwivedi who fixed the issue. @NamrataDwivedi are you able to share how you fixed the problem and also close the issue?

**Comment by NamrataDwivedi** [comment] 2018-04-09 05:47
Hello,
I am using an image picker version 0.26.7 and I replaced the code in the node modules->react-native-image-picker->android. 

Pls find the link for the replaced file:
https://github.com/react-community/react-native-image-picker/tree/develop/android

Also please write the the following in your project's android file:
  <provider
            android:name="com.imagepicker.FileProvider"
            android:authorities="${applicationId}.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths" />
        </provider>

Thanks

**Closed** 2018-04-09 05:50 UTC

**Comment by SurpassRabbit** [comment] 2018-09-10 08:28
andorid 4.1.1 simulator  not working

**Comment by Mohammad-Khalid23** [comment] 2018-09-15 12:28
Hello its working for me, i am using
**"react-native": "0.56.0"**
**"react-native-image-picker": "github:gengjiawen/react-native-image-picker#bugfix/android_photo_crash"**
this version is for android , because there was some issue in android ,
you can use it
